#!/usr/bin/env python

# this node generates random values for initial position, velocity and final position, velocity and time

import rospy
from ar_week5_test.msg import cubic_traj_params
import numpy as np

def random_points():
    # initialise node
    rospy.init_node('points_generator', anonymous=True)
    # initialise publisher topic "random points"
    pub = rospy.Publisher('random_points', cubic_traj_params, queue_size=10)
    rate = rospy.Rate(0.05) # publish once in every 20 seconds
    while not rospy.is_shutdown():

        # initialise cubic_traj_params message object
        random_params = cubic_traj_params()
        
        # generate random position and velocities and final time
        random_params.p0 = np.random.uniform(-10,10,1)
        random_params.pf = np.random.uniform(-10,10,1)
        random_params.v0 = np.random.uniform(-10,10,1)
        random_params.vf = np.random.uniform(-10,10,1)
        random_params.t0 = 0
        random_params.tf = np.random.uniform(5,10,1)

        rospy.loginfo(random_params)
        # publish to topic
        pub.publish(random_params)
        rate.sleep()

if __name__ == '__main__':
    try:
        random_points()
    except rospy.ROSInterruptException:
        pass
